language: python
python: 2.7
os:
  - linux
  - osx
env:
  matrix:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py34
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- travis_wait tox --skip-missing-interpreters -e $TOX_ENV
branches:
  only:
  - master
